"""mc ingest tables

Revision ID: 10256b584daf
Revises: 4858abe36ba9
Create Date: 2025-08-18 22:14:58.280587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10256b584daf'
down_revision: Union[str, Sequence[str], None] = '4858abe36ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mc_container_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('structure_id', sa.String(length=50), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('z', sa.Integer(), nullable=False),
    sa.Column('items_json', sa.JSON(), nullable=True),
    sa.Column('signs_json', sa.JSON(), nullable=True),
    sa.Column('opened_by_uuid', sa.String(length=64), nullable=True),
    sa.Column('opened_by_username', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('structure_id', 'x', 'y', 'z', name='uq_mc_container_struct_xyz')
    )
    op.create_index(op.f('ix_mc_container_snapshot_last_seen_at'), 'mc_container_snapshot', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_mc_container_snapshot_structure_id'), 'mc_container_snapshot', ['structure_id'], unique=False)
    op.create_table('mc_ingest_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('structure_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_sha256', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_sha256')
    )
    op.create_index('ix_mc_ingest_token_structure_active', 'mc_ingest_token', ['structure_id', 'active'], unique=False)
    op.create_index(op.f('ix_mc_ingest_token_structure_id'), 'mc_ingest_token', ['structure_id'], unique=False)
    op.create_table('mc_player_inventory_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('structure_id', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('inventory_json', sa.JSON(), nullable=True),
    sa.Column('hp_json', sa.JSON(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('structure_id', 'uuid', name='uq_mc_player_inv_struct_uuid')
    )
    op.create_index(op.f('ix_mc_player_inventory_snapshot_last_seen_at'), 'mc_player_inventory_snapshot', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_mc_player_inventory_snapshot_structure_id'), 'mc_player_inventory_snapshot', ['structure_id'], unique=False)
    op.create_table('mc_position_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('structure_id', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mc_position_history_struct_ts', 'mc_position_history', ['structure_id', 'ts'], unique=False)
    op.create_index('ix_mc_position_history_struct_uuid_ts', 'mc_position_history', ['structure_id', 'uuid', 'ts'], unique=False)
    op.create_index(op.f('ix_mc_position_history_structure_id'), 'mc_position_history', ['structure_id'], unique=False)
    op.create_index(op.f('ix_mc_position_history_ts'), 'mc_position_history', ['ts'], unique=False)
    op.create_index(op.f('ix_mc_position_history_uuid'), 'mc_position_history', ['uuid'], unique=False)
    op.create_table('mc_live_player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('structure_id', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hp_json', sa.JSON(), nullable=True),
    sa.Column('inventory_json', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('structure_id', 'uuid', name='uq_mc_live_player_struct_uuid')
    )
    op.create_index(op.f('ix_mc_live_player_last_seen_at'), 'mc_live_player', ['last_seen_at'], unique=False)
    op.create_index('ix_mc_live_player_struct_user', 'mc_live_player', ['structure_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_mc_live_player_structure_id'), 'mc_live_player', ['structure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mc_live_player_structure_id'), table_name='mc_live_player')
    op.drop_index('ix_mc_live_player_struct_user', table_name='mc_live_player')
    op.drop_index(op.f('ix_mc_live_player_last_seen_at'), table_name='mc_live_player')
    op.drop_table('mc_live_player')
    op.drop_index(op.f('ix_mc_position_history_uuid'), table_name='mc_position_history')
    op.drop_index(op.f('ix_mc_position_history_ts'), table_name='mc_position_history')
    op.drop_index(op.f('ix_mc_position_history_structure_id'), table_name='mc_position_history')
    op.drop_index('ix_mc_position_history_struct_uuid_ts', table_name='mc_position_history')
    op.drop_index('ix_mc_position_history_struct_ts', table_name='mc_position_history')
    op.drop_table('mc_position_history')
    op.drop_index(op.f('ix_mc_player_inventory_snapshot_structure_id'), table_name='mc_player_inventory_snapshot')
    op.drop_index(op.f('ix_mc_player_inventory_snapshot_last_seen_at'), table_name='mc_player_inventory_snapshot')
    op.drop_table('mc_player_inventory_snapshot')
    op.drop_index(op.f('ix_mc_ingest_token_structure_id'), table_name='mc_ingest_token')
    op.drop_index('ix_mc_ingest_token_structure_active', table_name='mc_ingest_token')
    op.drop_table('mc_ingest_token')
    op.drop_index(op.f('ix_mc_container_snapshot_structure_id'), table_name='mc_container_snapshot')
    op.drop_index(op.f('ix_mc_container_snapshot_last_seen_at'), table_name='mc_container_snapshot')
    op.drop_table('mc_container_snapshot')
    # ### end Alembic commands ###
