"""parrty leaders

Revision ID: 240b21048672
Revises: 4dbf7f2dc336
Create Date: 2025-08-20 19:34:31.180164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '240b21048672'
down_revision: Union[str, Sequence[str], None] = '4dbf7f2dc336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('leader_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_parties_leader_user_id'), 'parties', ['leader_user_id'], unique=False)
    op.create_foreign_key(None, 'parties', 'users', ['leader_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parties', type_='foreignkey')
    op.drop_index(op.f('ix_parties_leader_user_id'), table_name='parties')
    op.drop_column('parties', 'leader_user_id')
    # ### end Alembic commands ###
