"""message position

Revision ID: 47d939edac76
Revises: 240b21048672
Create Date: 2025-08-21 01:03:28.569255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47d939edac76'
down_revision: Union[str, Sequence[str], None] = '240b21048672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_position_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.String(length=50), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('position', postgresql.ENUM('TOP', 'LEFT', 'RIGHT', 'BOTTOM', name='mc_position'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_position_policy_structure_id'), 'message_position_policy', ['structure_id'], unique=False)
    op.create_index('uq_mpp_struct_kind', 'message_position_policy', ['structure_id', 'kind'], unique=True, postgresql_where=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_mpp_struct_kind', table_name='message_position_policy', postgresql_where=None)
    op.drop_index(op.f('ix_message_position_policy_structure_id'), table_name='message_position_policy')
    op.drop_table('message_position_policy')
    # ### end Alembic commands ###
