"""initial schema v2

Revision ID: 4858abe36ba9
Revises: 
Create Date: 2025-08-17 18:04:57.651123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4858abe36ba9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('code', name='uq_item_categories_code')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('TOWN', 'OUTPOST', 'MINE', 'PORT', 'OTHER', name='locationtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('z', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('external_kind', sa.Enum('IMPORT', 'EXPORT', name='external_kind'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_locations_export_per_structure', 'locations', ['structure_id'], unique=True, postgresql_where=sa.text("is_external IS true AND external_kind = 'EXPORT'"))
    op.create_index('uq_locations_import_per_structure', 'locations', ['structure_id'], unique=True, postgresql_where=sa.text("is_external IS true AND external_kind = 'IMPORT'"))
    op.create_table('movement_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('structure_id', 'code', name='uq_movement_reason_struct_code')
    )
    op.create_index('ix_movement_reasons_struct_active', 'movement_reasons', ['structure_id', 'is_active'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('structure_id', 'code', name='uq_roles_structure_code'),
    sa.UniqueConstraint('structure_id', 'name', name='uq_roles_structure_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('structure_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('stack_size', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('icon_image', sa.LargeBinary(), nullable=True),
    sa.Column('icon_mime_type', sa.String(length=64), nullable=True),
    sa.Column('icon_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('location_guild_masters',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('since', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'user_id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.String(length=50), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_structure_id'), 'trades', ['structure_id'], unique=False)
    op.create_index(op.f('ix_trades_timestamp'), 'trades', ['timestamp'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('discord_username', sa.String(length=64), nullable=True),
    sa.Column('minecraft_username', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('item_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('value_in_currency', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('structure_id', 'item_id', 'effective_from', name='uq_item_values_hist')
    )
    op.create_index('ix_item_values_lookup', 'item_values', ['structure_id', 'item_id', 'effective_from'], unique=False)
    op.create_table('player_inventory',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'item_id', 'structure_id', name='pk_player_inventory')
    )
    op.create_index('ix_player_inventory_user_item', 'player_inventory', ['user_id', 'item_id'], unique=False)
    op.create_table('structure_settings',
    sa.Column('structure_id', sa.String(length=50), nullable=False),
    sa.Column('currency_item_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['currency_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('structure_id')
    )
    op.create_table('trade_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=24), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('movement_reason_code', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(from_user_id IS NULL) <> (from_location_id IS NULL)', name='ck_trade_lines_from_party_xor'),
    sa.CheckConstraint('(to_user_id IS NULL) <> (to_location_id IS NULL)', name='ck_trade_lines_to_party_xor'),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_lines_id'), 'trade_lines', ['id'], unique=False)
    op.create_index('ix_trade_lines_item_trade', 'trade_lines', ['trade_id', 'item_id'], unique=False)
    op.create_index('ix_trade_lines_reason_code', 'trade_lines', ['movement_reason_code'], unique=False)
    op.create_table('player_inventory_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.String(length=16), nullable=False),
    sa.Column('delta_qty', sa.BigInteger(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('trade_line_id', sa.Integer(), nullable=False),
    sa.Column('movement_reason_code', sa.String(length=48), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_line_id'], ['trade_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pil_struct_time', 'player_inventory_ledger', ['structure_id', 'timestamp'], unique=False)
    op.create_index('ix_pil_user_item_time', 'player_inventory_ledger', ['user_id', 'item_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pil_user_item_time', table_name='player_inventory_ledger')
    op.drop_index('ix_pil_struct_time', table_name='player_inventory_ledger')
    op.drop_table('player_inventory_ledger')
    op.drop_index('ix_trade_lines_reason_code', table_name='trade_lines')
    op.drop_index('ix_trade_lines_item_trade', table_name='trade_lines')
    op.drop_index(op.f('ix_trade_lines_id'), table_name='trade_lines')
    op.drop_table('trade_lines')
    op.drop_table('structure_settings')
    op.drop_index('ix_player_inventory_user_item', table_name='player_inventory')
    op.drop_table('player_inventory')
    op.drop_index('ix_item_values_lookup', table_name='item_values')
    op.drop_table('item_values')
    op.drop_table('user_roles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_trades_timestamp'), table_name='trades')
    op.drop_index(op.f('ix_trades_structure_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('location_guild_masters')
    op.drop_table('items')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index('ix_movement_reasons_struct_active', table_name='movement_reasons')
    op.drop_table('movement_reasons')
    op.drop_index('uq_locations_import_per_structure', table_name='locations', postgresql_where=sa.text("is_external IS true AND external_kind = 'IMPORT'"))
    op.drop_index('uq_locations_export_per_structure', table_name='locations', postgresql_where=sa.text("is_external IS true AND external_kind = 'EXPORT'"))
    op.drop_table('locations')
    op.drop_table('item_categories')
    # ### end Alembic commands ###
