"""mc messages and parties

Revision ID: 4dbf7f2dc336
Revises: 10256b584daf
Create Date: 2025-08-20 17:33:44.950391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dbf7f2dc336'
down_revision: Union[str, Sequence[str], None] = '10256b584daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=24), server_default='CHAT', nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deliver_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requires_ack', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('priority', sa.String(length=16), server_default='NORMAL', nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_structure_id'), 'messages', ['structure_id'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('structure_id', 'name', name='uq_parties_struct_name')
    )
    op.create_index(op.f('ix_parties_structure_id'), 'parties', ['structure_id'], unique=False)
    op.create_table('message_recipient_status',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='QUEUED', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id')
    )
    op.create_index('ix_mrs_msg_status', 'message_recipient_status', ['message_id', 'status'], unique=False)
    op.create_index('ix_mrs_user_status', 'message_recipient_status', ['user_id', 'status'], unique=False)
    op.create_table('message_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(user_id IS NOT NULL) <> (party_id IS NOT NULL)', name='ck_message_targets_xor'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'party_id', name='uq_message_targets_msg_party'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_targets_msg_user')
    )
    op.create_index(op.f('ix_message_targets_message_id'), 'message_targets', ['message_id'], unique=False)
    op.create_table('party_members',
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('party_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('party_members')
    op.drop_index(op.f('ix_message_targets_message_id'), table_name='message_targets')
    op.drop_table('message_targets')
    op.drop_index('ix_mrs_user_status', table_name='message_recipient_status')
    op.drop_index('ix_mrs_msg_status', table_name='message_recipient_status')
    op.drop_table('message_recipient_status')
    op.drop_index(op.f('ix_parties_structure_id'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_messages_structure_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
