"""chest_sync_tables

Revision ID: 659830dae6ac
Revises: 779bb31f1388
Create Date: 2025-11-28 23:31:43.891121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '659830dae6ac'
down_revision: Union[str, Sequence[str], None] = '779bb31f1388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chest_sync_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('structure_id', sa.String(length=50), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('z', sa.Integer(), nullable=False),
    sa.Column('items_json', sa.JSON(), nullable=True),
    sa.Column('signs_json', sa.JSON(), nullable=True),
    sa.Column('opened_by_uuid', sa.String(length=64), nullable=True),
    sa.Column('opened_by_username', sa.String(length=64), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chest_sync_history_recorded_at'), 'chest_sync_history', ['recorded_at'], unique=False)
    op.create_index('ix_chest_sync_history_struct_recorded', 'chest_sync_history', ['structure_id', 'recorded_at'], unique=False)
    op.create_index('ix_chest_sync_history_struct_xyz_recorded', 'chest_sync_history', ['structure_id', 'x', 'y', 'z', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_chest_sync_history_structure_id'), 'chest_sync_history', ['structure_id'], unique=False)
    op.create_table('chest_sync_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('structure_id', sa.String(length=50), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('z', sa.Integer(), nullable=False),
    sa.Column('world', sa.String(length=64), nullable=True),
    sa.Column('items_json', sa.JSON(), nullable=True),
    sa.Column('signs_json', sa.JSON(), nullable=True),
    sa.Column('opened_by_uuid', sa.String(length=64), nullable=True),
    sa.Column('opened_by_username', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('structure_id', 'x', 'y', 'z', name='uq_chest_sync_struct_xyz')
    )
    op.create_index(op.f('ix_chest_sync_snapshot_last_seen_at'), 'chest_sync_snapshot', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_chest_sync_snapshot_structure_id'), 'chest_sync_snapshot', ['structure_id'], unique=False)
    op.create_index('ix_chest_sync_struct_last_seen', 'chest_sync_snapshot', ['structure_id', 'last_seen_at'], unique=False)
    op.create_index('ix_chest_sync_struct_xyz', 'chest_sync_snapshot', ['structure_id', 'x', 'y', 'z'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chest_sync_struct_xyz', table_name='chest_sync_snapshot')
    op.drop_index('ix_chest_sync_struct_last_seen', table_name='chest_sync_snapshot')
    op.drop_index(op.f('ix_chest_sync_snapshot_structure_id'), table_name='chest_sync_snapshot')
    op.drop_index(op.f('ix_chest_sync_snapshot_last_seen_at'), table_name='chest_sync_snapshot')
    op.drop_table('chest_sync_snapshot')
    op.drop_index(op.f('ix_chest_sync_history_structure_id'), table_name='chest_sync_history')
    op.drop_index('ix_chest_sync_history_struct_xyz_recorded', table_name='chest_sync_history')
    op.drop_index('ix_chest_sync_history_struct_recorded', table_name='chest_sync_history')
    op.drop_index(op.f('ix_chest_sync_history_recorded_at'), table_name='chest_sync_history')
    op.drop_table('chest_sync_history')
    # ### end Alembic commands ###
