"""simplify_user_model_use_username_only

Revision ID: 779bb31f1388
Revises: dc0e8959a309
Create Date: 2025-11-25 20:11:36.223060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '779bb31f1388'
down_revision: Union[str, Sequence[str], None] = 'dc0e8959a309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Clean up orphaned records before adding foreign key constraints
    op.execute("DELETE FROM message_recipient_status WHERE user_id NOT IN (SELECT id FROM users)")
    op.execute("DELETE FROM message_targets WHERE user_id NOT IN (SELECT id FROM users)")
    op.execute("DELETE FROM party_members WHERE user_id NOT IN (SELECT id FROM users)")
    op.execute("DELETE FROM player_inventory WHERE user_id NOT IN (SELECT id FROM users)")
    op.execute("DELETE FROM player_inventory_ledger WHERE user_id NOT IN (SELECT id FROM users)")
    op.execute("DELETE FROM mc_live_player WHERE user_id NOT IN (SELECT id FROM users)")
    op.execute("DELETE FROM trades WHERE user_id NOT IN (SELECT id FROM users)")
    op.execute("DELETE FROM trade_lines WHERE from_user_id NOT IN (SELECT id FROM users) OR to_user_id NOT IN (SELECT id FROM users)")
    op.execute("DELETE FROM messages WHERE created_by_user_id NOT IN (SELECT id FROM users)")
    op.execute("DELETE FROM parties WHERE created_by_user_id NOT IN (SELECT id FROM users) OR (leader_user_id IS NOT NULL AND leader_user_id NOT IN (SELECT id FROM users))")
    op.execute("DELETE FROM structure_settings WHERE updated_by_user_id NOT IN (SELECT id FROM users)")
    op.execute("DELETE FROM item_values WHERE created_by_user_id IS NOT NULL AND created_by_user_id NOT IN (SELECT id FROM users)")
    op.execute("DELETE FROM items WHERE created_by_user_id IS NOT NULL AND created_by_user_id NOT IN (SELECT id FROM users)")

    op.drop_index(op.f('ix_auth_audit_event'), table_name='auth_audit_log')
    op.drop_index(op.f('ix_auth_audit_mc'), table_name='auth_audit_log')
    op.drop_index(op.f('ix_auth_audit_user'), table_name='auth_audit_log')
    op.create_index(op.f('ix_auth_audit_log_created_at'), 'auth_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_audit_log_event_type'), 'auth_audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_auth_audit_log_mc_uuid'), 'auth_audit_log', ['mc_uuid'], unique=False)
    op.create_foreign_key(None, 'item_values', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'items', 'users', ['created_by_user_id'], ['id'])
    op.drop_index(op.f('ix_magic_tokens_expires'), table_name='magic_login_tokens')
    op.drop_index(op.f('ix_magic_tokens_token'), table_name='magic_login_tokens')
    op.drop_index(op.f('ix_magic_tokens_user'), table_name='magic_login_tokens')
    op.drop_constraint(op.f('magic_login_tokens_token_key'), 'magic_login_tokens', type_='unique')
    op.create_index(op.f('ix_magic_login_tokens_expires_at'), 'magic_login_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_magic_login_tokens_token'), 'magic_login_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_magic_login_tokens_user_id'), 'magic_login_tokens', ['user_id'], unique=False)
    op.create_foreign_key(None, 'mc_live_player', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'message_recipient_status', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'message_targets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'users', ['created_by_user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'parties', 'users', ['created_by_user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'parties', 'users', ['leader_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'party_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'player_inventory', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'player_inventory_ledger', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_roles_structure'), table_name='roles')
    op.create_index(op.f('ix_roles_structure_id'), 'roles', ['structure_id'], unique=False)
    op.drop_index(op.f('ix_join_codes_active'), table_name='structure_join_codes')
    op.drop_index(op.f('ix_join_codes_code'), table_name='structure_join_codes')
    op.drop_index(op.f('ix_join_codes_structure'), table_name='structure_join_codes')
    op.drop_constraint(op.f('structure_join_codes_code_key'), 'structure_join_codes', type_='unique')
    op.create_index(op.f('ix_structure_join_codes_code'), 'structure_join_codes', ['code'], unique=True)
    op.create_index(op.f('ix_structure_join_codes_structure_id'), 'structure_join_codes', ['structure_id'], unique=False)
    op.create_foreign_key(None, 'structure_settings', 'users', ['updated_by_user_id'], ['id'])
    op.drop_index(op.f('ix_structures_is_active'), table_name='structures')
    op.create_foreign_key(None, 'trade_lines', 'users', ['from_user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'trade_lines', 'users', ['to_user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'trades', 'users', ['user_id'], ['id'])
    # Step 1: Add username column as nullable first
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))

    # Step 2: Copy mc_name to username for all existing users
    op.execute("UPDATE users SET username = mc_name WHERE username IS NULL")

    # Step 3: Now make username NOT NULL
    op.alter_column('users', 'username', nullable=False)

    # Step 4: Drop old constraints and indexes
    op.drop_index(op.f('ix_users_login_name'), table_name='users')
    op.drop_index(op.f('ix_users_structure'), table_name='users')
    op.drop_constraint(op.f('users_login_name_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_mc_uuid_key'), 'users', type_='unique')

    # Step 5: Create new indexes
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # Step 6: Drop old columns
    op.drop_column('users', 'login_name')
    op.drop_column('users', 'mc_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mc_name', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('login_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('users_mc_uuid_key'), 'users', ['mc_uuid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_login_name_key'), 'users', ['login_name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_structure'), 'users', ['structure_id'], unique=False)
    op.create_index(op.f('ix_users_login_name'), 'users', ['login_name'], unique=True)
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trade_lines', type_='foreignkey')
    op.drop_constraint(None, 'trade_lines', type_='foreignkey')
    op.create_index(op.f('ix_structures_is_active'), 'structures', ['is_active'], unique=False)
    op.drop_constraint(None, 'structure_settings', type_='foreignkey')
    op.drop_index(op.f('ix_structure_join_codes_structure_id'), table_name='structure_join_codes')
    op.drop_index(op.f('ix_structure_join_codes_code'), table_name='structure_join_codes')
    op.create_unique_constraint(op.f('structure_join_codes_code_key'), 'structure_join_codes', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_join_codes_structure'), 'structure_join_codes', ['structure_id'], unique=False)
    op.create_index(op.f('ix_join_codes_code'), 'structure_join_codes', ['code'], unique=True)
    op.create_index(op.f('ix_join_codes_active'), 'structure_join_codes', ['is_active', 'expires_at'], unique=False)
    op.drop_index(op.f('ix_roles_structure_id'), table_name='roles')
    op.create_index(op.f('ix_roles_structure'), 'roles', ['structure_id'], unique=False)
    op.drop_constraint(None, 'player_inventory_ledger', type_='foreignkey')
    op.drop_constraint(None, 'player_inventory', type_='foreignkey')
    op.drop_constraint(None, 'party_members', type_='foreignkey')
    op.drop_constraint(None, 'parties', type_='foreignkey')
    op.drop_constraint(None, 'parties', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'message_targets', type_='foreignkey')
    op.drop_constraint(None, 'message_recipient_status', type_='foreignkey')
    op.drop_constraint(None, 'mc_live_player', type_='foreignkey')
    op.drop_index(op.f('ix_magic_login_tokens_user_id'), table_name='magic_login_tokens')
    op.drop_index(op.f('ix_magic_login_tokens_token'), table_name='magic_login_tokens')
    op.drop_index(op.f('ix_magic_login_tokens_expires_at'), table_name='magic_login_tokens')
    op.create_unique_constraint(op.f('magic_login_tokens_token_key'), 'magic_login_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_magic_tokens_user'), 'magic_login_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_magic_tokens_token'), 'magic_login_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_magic_tokens_expires'), 'magic_login_tokens', ['expires_at'], unique=False)
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'item_values', type_='foreignkey')
    op.drop_index(op.f('ix_auth_audit_log_mc_uuid'), table_name='auth_audit_log')
    op.drop_index(op.f('ix_auth_audit_log_event_type'), table_name='auth_audit_log')
    op.drop_index(op.f('ix_auth_audit_log_created_at'), table_name='auth_audit_log')
    op.create_index(op.f('ix_auth_audit_user'), 'auth_audit_log', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_auth_audit_mc'), 'auth_audit_log', ['mc_uuid'], unique=False)
    op.create_index(op.f('ix_auth_audit_event'), 'auth_audit_log', ['event_type', 'created_at'], unique=False)
    # ### end Alembic commands ###
